mv BaseBuiltinModel.php class-base-builtin-model.php
mv BaseCptCtrl.php class-base-cpt-ctrl.php
mv BaseCptModel.php class-base-cpt-model.php
mv BaseCtaxCtrl.php class-base-ctax-ctrl.php
mv BaseCtaxModel.php class-base-ctax-model.php
mv BaseCtrl.php class-base-ctrl.php
mv BaseModel.php class-base-model.php
mv Config.php class-config.php
mv CtrlFactory.php class-ctrl-factory.php
mv Db.php class-db.php
mv Exceptions.php class-exceptions.php
mv index.php class-index.php
mv Inflector.php class-inflector.php
mv ModelFactory.php class-model-factory.php
mv Utils.php class-utils.php
